"""The offline basemap must actually cover the zones it sits under.

`frontend/public/basemap.jpg` is a pre-built image the dashboard falls back to when live
tiles cannot be fetched, georeferenced by `frontend/src/basemap-bounds.json`. Both are
generated by `tools/build_offline_basemap.py`.

The failure this guards against is silent and only shows up with no internet, which is
precisely when nobody can fix it: someone edits `zones.geojson`, nobody re-runs the tool,
and at the venue the fallback renders a map of the wrong place with the polygons hanging off
its edge. A judge would see it before we did.
"""

import json
import pathlib

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
ZONES = ROOT / "data" / "samples" / "zones.geojson"
BOUNDS = ROOT / "frontend" / "src" / "basemap-bounds.json"
IMAGE = ROOT / "frontend" / "public" / "basemap.jpg"


def _zone_bbox() -> tuple[float, float, float, float]:
    data = json.loads(ZONES.read_text())
    features = data["features"] if data.get("type") == "FeatureCollection" else [data]
    lons: list[float] = []
    lats: list[float] = []

    def walk(coords) -> None:
        if isinstance(coords[0], (int, float)):
            lons.append(coords[0])
            lats.append(coords[1])
            return
        for part in coords:
            walk(part)

    for feature in features:
        walk(feature["geometry"]["coordinates"])
    return min(lons), min(lats), max(lons), max(lats)


def test_the_basemap_asset_and_its_bounds_both_exist():
    assert IMAGE.exists(), f"missing {IMAGE} -- run tools/build_offline_basemap.py"
    assert BOUNDS.exists(), f"missing {BOUNDS} -- run tools/build_offline_basemap.py"


def test_bounds_are_well_formed():
    (south, west), (north, east) = json.loads(BOUNDS.read_text())["bounds"]
    assert south < north, "south must be below north -- bounds are [[S, W], [N, E]]"
    assert west < east, "west must be left of east"


def test_the_basemap_covers_every_zone():
    """Not 'overlaps' -- contains. A polygon off the edge of the image is the whole bug."""
    west, south, east, north = _zone_bbox()
    (b_south, b_west), (b_north, b_east) = json.loads(BOUNDS.read_text())["bounds"]

    assert b_west <= west, f"basemap starts at lon {b_west}, zones start at {west}"
    assert b_east >= east, f"basemap ends at lon {b_east}, zones end at {east}"
    assert b_south <= south, f"basemap starts at lat {b_south}, zones start at {south}"
    assert b_north >= north, f"basemap ends at lat {b_north}, zones end at {north}"


def test_the_basemap_leaves_context_around_the_zones():
    """Edge-to-edge would look like a bug. The generator pads; check the padding survived."""
    west, south, east, north = _zone_bbox()
    (b_south, b_west), (b_north, b_east) = json.loads(BOUNDS.read_text())["bounds"]
    assert (east - west) * 1.2 < (b_east - b_west)
    assert (north - south) * 1.2 < (b_north - b_south)


def test_the_asset_stays_small_enough_to_ship():
    """It is committed and served to every visitor. A stray full-resolution export hurts."""
    size_mb = IMAGE.stat().st_size / (1024 * 1024)
    assert size_mb < 1.5, f"basemap.jpg is {size_mb:.1f} MB -- lower MAX_WIDTH or JPEG_QUALITY"


@pytest.mark.parametrize("field", ["bounds", "zoom", "attribution"])
def test_bounds_file_keeps_its_attribution_and_provenance(field):
    """The tiles are OpenStreetMap's. The attribution has to travel with the image."""
    assert field in json.loads(BOUNDS.read_text())
