#!/usr/bin/env python3
"""Stitch an offline fallback basemap for the demo city from OpenStreetMap tiles.

Why this exists: the dashboard's map pulls tiles live. At a venue with no working wifi the
tiles never arrive and the map renders as a blank grey box -- and the map is the demo. This
builds one georeferenced image of the demo area that the frontend falls back to when tile
requests fail. The zone polygons and pins are vector and keep working either way.

Run it only when the zone set changes. It writes:

    frontend/public/basemap.jpg          the stitched image
    frontend/src/basemap-bounds.json     its exact [[south, west], [north, east]] bounds

Needs Pillow and nothing else -- the fetch is stdlib urllib on purpose, so this tool does
not drag a dependency into the backend it has nothing to do with.

Usage:
    python tools/build_offline_basemap.py

OSM tile policy: this is a one-off fetch of a few dozen tiles with a real User-Agent and a
delay between requests. Do not turn it into a loop over a whole country -- that is exactly
what their policy forbids, and there are commercial providers for that.
"""

import json
import math
import pathlib
import time
import urllib.request
from io import BytesIO

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
ZONES = ROOT / "data" / "samples" / "zones.geojson"
OUT_IMAGE = ROOT / "frontend" / "public" / "basemap.jpg"
OUT_BOUNDS = ROOT / "frontend" / "src" / "basemap-bounds.json"

ZOOM = 14
PAD_RATIO = 0.55  # context around the zone grid, roughly matching the live default view
MAX_WIDTH = 1600  # downscale target; keeps the asset well under a megabyte
JPEG_QUALITY = 78
USER_AGENT = "NeerDrishti-AI/0.1 (Decode SIH 2026 Team Zeniths; one-off demo basemap build)"
TILE = 256


def zone_bbox() -> tuple[float, float, float, float]:
    data = json.loads(ZONES.read_text())
    features = data["features"] if data.get("type") == "FeatureCollection" else [data]
    lons: list[float] = []
    lats: list[float] = []

    def walk(coords) -> None:
        if isinstance(coords[0], (int, float)):
            lons.append(coords[0])
            lats.append(coords[1])
            return
        for part in coords:
            walk(part)

    for feature in features:
        walk(feature["geometry"]["coordinates"])
    return min(lons), min(lats), max(lons), max(lats)


def deg2tile(lat: float, lon: float, zoom: int) -> tuple[int, int]:
    n = 2**zoom
    x = int((lon + 180.0) / 360.0 * n)
    lat_rad = math.radians(lat)
    y = int((1.0 - math.log(math.tan(lat_rad) + 1 / math.cos(lat_rad)) / math.pi) / 2.0 * n)
    return x, y


def tile2deg(x: int, y: int, zoom: int) -> tuple[float, float]:
    """North-west corner of tile (x, y). Passing x+1 / y+1 gives the south-east corner."""
    n = 2**zoom
    lon = x / n * 360.0 - 180.0
    lat = math.degrees(math.atan(math.sinh(math.pi * (1 - 2 * y / n))))
    return lat, lon


def main() -> int:
    west, south, east, north = zone_bbox()
    pad_x = (east - west) * PAD_RATIO
    pad_y = (north - south) * PAD_RATIO
    west, south, east, north = west - pad_x, south - pad_y, east + pad_x, north + pad_y

    x0, y0 = deg2tile(north, west, ZOOM)
    x1, y1 = deg2tile(south, east, ZOOM)
    cols, rows = x1 - x0 + 1, y1 - y0 + 1
    print(f"zoom {ZOOM}: {cols}x{rows} = {cols * rows} tiles")

    canvas = Image.new("RGB", (cols * TILE, rows * TILE))
    for i, x in enumerate(range(x0, x1 + 1)):
        for j, y in enumerate(range(y0, y1 + 1)):
            url = f"https://tile.openstreetmap.org/{ZOOM}/{x}/{y}.png"
            request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(request, timeout=30) as response:
                payload = response.read()
            canvas.paste(Image.open(BytesIO(payload)).convert("RGB"), (i * TILE, j * TILE))
            time.sleep(0.12)  # be a good citizen
        print(f"  column {i + 1}/{cols}")

    # Bounds of the stitched grid are the tile edges, not the padded bbox we asked for.
    # Getting this wrong offsets the whole basemap under the polygons.
    top_lat, left_lon = tile2deg(x0, y0, ZOOM)
    bottom_lat, right_lon = tile2deg(x1 + 1, y1 + 1, ZOOM)

    if canvas.width > MAX_WIDTH:
        height = round(canvas.height * MAX_WIDTH / canvas.width)
        canvas = canvas.resize((MAX_WIDTH, height), Image.LANCZOS)

    OUT_IMAGE.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(OUT_IMAGE, "JPEG", quality=JPEG_QUALITY, optimize=True, progressive=True)
    OUT_BOUNDS.write_text(
        json.dumps(
            {
                "bounds": [[bottom_lat, left_lon], [top_lat, right_lon]],
                "zoom": ZOOM,
                "attribution": "© OpenStreetMap contributors",
                "note": "Generated by tools/build_offline_basemap.py -- do not hand-edit.",
            },
            indent=2,
        )
        + "\n"
    )
    size_kb = OUT_IMAGE.stat().st_size / 1024
    print(f"wrote {OUT_IMAGE.relative_to(ROOT)}  {canvas.size[0]}x{canvas.size[1]}  {size_kb:.0f} KB")
    print(f"wrote {OUT_BOUNDS.relative_to(ROOT)}  bounds=[[{bottom_lat:.6f}, {left_lon:.6f}], "
          f"[{top_lat:.6f}, {right_lon:.6f}]]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
